### ISSUE TITLE
Why is the project abandoned?

### ISSUE THREAD

**Issue by angryziber** [mysociety/yournextmp-popit#1002]
Hi! I had the idea to build a similar platform and found this one.
However, it doesn't seem to be maintained anymore. Why? What didn't work?

**Comment by struan** [comment]
It did, and does work fine. mySociety stopped working on this as we didn't have the resources to carry on maintaining it. However Democracy Club in the UK have continued to develop it for use in UK elections, along with a number of other tools that use the information gathered using yournextrepresentative. You can find the current codebase here:

https://github.com/DemocracyClub/yournextrepresentative

And details about DemocracyClub here:

https://democracyclub.org.uk/
