### ISSUE TITLE
update parties from electoral commission

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#112]
The party list is now a bit out of date - we got this report by email, for example, pointing out a new party that was registered very recently:

> How long does it take for the party list to get updated? A candidate in Cardiff North has recently registered a new party called "Alter Change - Politics. Only Different". It was registered on 8th Dec 2014.

We should set up a regular import from @symroe's scraped electoral commission data. This is (approximately) just a matter of running `candidates_update_popit_parties_from_ec_data` after updating the submodule.

**Comment by symroe** [comment]
I've just pushed an update to the parties data.  There are a few new fields (including geocoded party address) and a few new parties.

Also, I've cleaned out the `[De-registered *]` noise from the party names.  They are now proper names, with a new `deregistered_date` taken from the party name field.
