### ISSUE TITLE
Better instructions for twitter field

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/yournextmp-popit#131]
It's natural to want to include the '@' character in the Twitter field, but this will fail validation. 

To make this clearer, precede the field with the @ sign, as below 

![twitter-field](https://cloud.githubusercontent.com/assets/2292925/5677702/f1bde6fa-97e1-11e4-9096-cf00391115da.png)

**Comment by zarino** [comment]
This is one of the changes I was imagining in #130.

I've added it, more explicitly, to the above ticket.

**Comment by mhl** [comment]
For the moment I've changed the validation to strip out any `@` prefix (3f82dd9b967e0f4018)
