### ISSUE TITLE
improve the design of the person view page

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#146]
At the moment, the candidate view page is basically just looks like a table of data:

![ynmp-people-view](https://cloud.githubusercontent.com/assets/7907/5778487/89908828-9d93-11e4-84fa-44af31ce9a41.png)

I thought this was fine, since it suggests "here's a data source you can use" and we didn't necessarily want it to be a destination page to find out about candidates; however, various people have convinced me that this is wrong - we are very high in Google rankings for many candidate-related searches and it's missing an opportunity not providing an engaging page when people follow those links.

Hopefully this should be flexible enough to include links out to social media platforms we haven't included yet (e.g. linkedin, youtube) and potentially allow us to include past election leaflets from electionleaflets.org, etc.

**Comment by philipjohn** [comment]
:+1:

**Comment by zarino** [comment]
Worth adding that the "Help by editing this information" message should much further up the page, as per #138.

**Comment by zarino** [comment]
Pull request submitted: #159.

![profile](https://cloud.githubusercontent.com/assets/739624/5859837/36743416-a255-11e4-9fe3-d11a244ff02a.png)

**Comment by tfgg** [comment]
Minor bikeshedding and probably for another time - but is the party too de-emphasized in this new design? It wasn't very prominent beforehand, and now it's quite hard to spot.

**Comment by dracos** [comment]
Could it perhaps be in the header, "Foo Party Candidate for Bar in 2015"?

**Comment by tfgg** [comment]
@dracos was replying to my comment below which I'd just moved to the pull request. Sorry!

Minor bikeshedding and probably for another time - but is the party too de-emphasized in this new design? It wasn't very prominent beforehand, and now it's quite hard to spot.

**Comment by zarino** [comment]
> Could it perhaps be in the header, "Foo Party Candidate for Bar in 2015"?

I thought exactly this when I was doing the new layout. Although I worried that long party names might make the header impenetrable?

“United Kingdom Independence Party (UKIP) candidate for *Some Constituency* in 2015" ?

What do you think @dracos?

@tfgg – I can make the party more prominent in the "Constituencies" section if you think it would help.

**Comment by mhl** [comment]
On the gender issue, perhaps move that to a Demographics section at the bottom (and we could add age / date of birth in that section too).

@zarino If it helps with making the party more obvious, we have many party logos in the PopIt instance so I can easily make them available in the template. They're all black on a white background, I think. e.g.:

![Liberal Democrat logo from PopIt](https://yournextmp.popit.mysociety.org/image-proxy/https%3A%2F%2Fyournextmp.popit.mysociety.org%2Forganizations%2Fimages%2F54bea4ae5a9c3744778f9b29%2Fparty%3A90/128/0)
