### ISSUE TITLE
Numbers for party/constituency seem wrong

### ISSUE THREAD

**Issue by xavriley** [mysociety/yournextmp-popit#149]
At the time of writing, https://yournextmp.com/numbers/parties shows the number of known candidates for the LibDems to be 298. However the LibDems are listing their 2015 candidates here http://www.libdems.org.uk/general_election_candidates and I only count 175.

Could there be an additional filter for numbers to drill down to a GE year? That way we can compare large lists of candidates more easily (and potentially spot errors)

**Comment by tfgg** [comment]
Andy's spreadsheet here:

https://docs.google.com/spreadsheet/ccc?key=0At91c3wX1Wu5dFkzTjFrRmJRN3F6ODBTTEs4NGFhcUE#gid=0

has 320 known candidates for the liberal democrats in 2015. Could it be the case that the libdems aren't updating that page very often?

**Comment by andylolz** [comment]
Yep – what @tfgg said. I bodged this together just to check:
https://gist.github.com/andylolz/1963c995fe93af330714

It shows for instance that [this page](http://www.northwestlibdems.org.uk/2015-candidates/) includes ~22 candidates who don’t appear on the [central lib dems candidate list](http://www.libdems.org.uk/general_election_candidates).

> Could there be an additional filter for numbers to drill down to a GE year? That way we can compare large lists of candidates more easily (and potentially spot errors)

More functionality on the numbers page would be ace. Note, though, that the numbers shown on that page currently are exclusively for GE2015.

**Comment by xavriley** [comment]
Cool thanks for clearing that up.

I trust @andylolz numbers more than the LibDems any day!

I was writing a similar script but you beat me to it. Whilst looking I did notice a lot of potential duplicates here though https://yournextmp.popit.mysociety.org/organizations/party:90#members

```
>> doc2.css(".memberships .view-mode a:first-of-type").map {|x| x.text }.sort.uniq.length
=> 790
>> doc2.css(".memberships .view-mode a:first-of-type").map {|x| x.text }.sort.length
=> 929
```

Not sure if that's another issue though. I'll close this one for now as my original query is answered.

**Comment by tfgg** [comment]
Ok :)

If I understand your script, I believe that would double count people who stood in 2010 and are standing again in 2015. Not to say that there aren't duplicate candidates - I've been merging quite a few.
