### ISSUE TITLE
get an SSL certificate for YourNextMP.com

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#15]
... after talking to Edmund about changing the DNS.

**Comment by mhl** [comment]
The certificate is deployed now, so https://yournextmp.com works to some extent - I hope that the following pull request will sort out the remaining issues: https://github.com/mysociety/yournextmp-popit/pull/134

**Comment by edent** [comment]
The sign up page doesn't automatically redirect to https.  Manually editing the URL seems to work.

Would suggest making it mandatory to prevent password sniffing etc.

**Comment by dracos** [comment]
@edent Yes, this is just the first step as Mark says; those would both be fixed by the #134 Mark refers to :)

**Comment by mhl** [comment]
Hopefully this is all sorted now, and any non-secure requests are now redirecting to the corresponding https page.
