### ISSUE TITLE
API: `next_url` and `prev_url` lose query parameter

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextmp-popit#150]
e.g. http://yournextmp.popit.mysociety.org/api/v0.1/search/persons?q=party:%27Liberal%20Democrats%27&page=2

Both `next_url` and `prev_url` are missing the `q` param, so return unexpected results.

**Comment by andylolz** [comment]
I don’t know if this is actually a problem with `mysociety/popit-api`… Haven’t investigated further I’m afraid.

**Comment by tfgg** [comment]
I think this is related to this issue I made https://github.com/mysociety/popit/issues/711

(now realising that it should probably be in the popit-api repo)

**Comment by andylolz** [comment]
You’re right – we should probably close both of these!

Your ticket is better, as it’s a bit more general. Do you want to move that one to popit-api? I’ll close this one.
