### ISSUE TITLE
Broken Facebook URLs in Facebook field

### ISSUE THREAD

**Issue by edent** [mysociety/yournextmp-popit#153]
Noticed this on a couple of candidates.  Eg https://yournextmp.com/person/4500

```
Full version (67d53769566ec13e):
{
    "birth_date": null, 
    "facebook_personal_url": "fb/KMBlundell", 
...
```

As you can see, `fb/XYZ` is not a valid URL.  It should be `fb.com/XYZ` which will then redirect to the correct URL.

Not sure how it got ingested that way - the history shows it popping back and forth.  I'm fairly sure I've seen a few like it.

**Comment by andylolz** [comment]
Good spot, @edent.

In this instance (and possibly others) this looks like a problem with the lib dem scraper. Here’s the source:
http://www.libdems.org.uk/kelly_marie_blundell

You can see the anchor text is an invalid URL, but the href is correct. I think this is the relevant bit of the scraper:
https://github.com/mhl/UK-Political-Parties/blob/all-scrapers/ppcs/libdem-scraper.py#L74-L92

**Comment by edent** [comment]
I've corrected all the "fb/" links in the data.
