### ISSUE TITLE
Tail of the “Not standing again” bubble points to “Standing again”

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextmp-popit#156]
When I click **Not standing again**, I see:

![screen shot 2015-01-22 at 11 17 47](https://cloud.githubusercontent.com/assets/464193/5854694/84e15944-a228-11e4-9668-d40b13d007a3.png)

Every time I do it, the tail makes me think I’ve clicked the wrong button.

**Comment by mhl** [comment]
sigh. I was careful to make sure that this was working in 08b45c648c60, and worked fine until cdbe66859de30798 after which the arrow always pointed to the right hand box - at 7fe55a97a7081804e9 and thereafter the arrow always points to the right-hand box. Should be an easy fix, anyway.

**Comment by andylolz** [comment]
Ha! It sounds like I just caught it on the wrong day! :)

**Comment by andylolz** [comment]
V nice. Thanks!
