### ISSUE TITLE
Following password reset email link causes cert error

### ISSUE THREAD

**Issue by garethrees** [mysociety/yournextmp-popit#160]
Link in email is https://yournextmp.mysociety.org not https://yournextmp.com/

![screen shot 2015-01-23 at 15 44 50](https://cloud.githubusercontent.com/assets/282788/5877424/691291ac-a317-11e4-9610-848efcc35a74.png)

Mail text is:

```
You're receiving this e-mail because you or someone else has requested a password for your user account at yournextmp.mysociety.org.
It can be safely ignored if you did not request a password reset. Click the link below to reset your password.

https://yournextmp.mysociety.org/accounts/password/reset/key/d-3REDACTED/

In case you forgot, your username is garethrees.

Thanks for using our site!
```

**Comment by mhl** [comment]
Thanks for reporting that, @garethrees - I've fixed that now. (The domain in the sites table was still yournextmp.mysociety.org instead of yournextmp.com.)
