### ISSUE TITLE
Candidates can be standing for more than one party

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextmp-popit#168]
As pointed out by Janet McKnight [1], there exist "Labour & Co-operative" candidates who are standing for *both* the Labour Party and Co-operative Party. Currently the YNMP data model only allows a candidate to be standing for one party in any particular election.

Currently 31 Labour MPs are also Co-Operative party members, including Ed Balls [2]. According to [3], the Co-operative party only stands candidates jointly with the Labour Party, so there are no independents. Thus, as a temporary measure, I've suggested that Labour & Co-op candidates are marked as Co-op party candidates.

In addition, @symroe  and I investigated the party descriptions in the Electoral Commission rules and dataset. Sym found that candidates can stand for an arbitrary number of parties, and that candidates standing jointly can use a "joint description" common to between the parties they are standing for. There are 17 parties with registered joint descriptions, e.g. the Labour and Co-operative ones are [4][5]

"Labour and Co-operative Party Candidate (Joint Description with Co-operative Party)"
"Labour and Co-operative Party Candidate (Joint Description with Labour Party)"

So instances of possible joint parties could be automatically discovered by stripping the brackets and looking for matching pairs of descriptions.

Given all that, ideas for fixing:

1. The popit data model allows extra party memberships to be added, so there's nothing stopping us adding both parties as their 2010/2015 party there. If there is more than one party added, the candidate could be described using the appropriate joint description rather than the party primary name.

2. We could use the detected joint descriptions to make "virtual parties" which use the joint description as its name. These would appear like other parties in the party drop-down list. Candidates would have to somehow appear in statistics for both parties, though.

3. A sort of merger of the above two where the popit datamodel would show two party memberships, but the YNMP datamodel would use virtual parties, simplifying the UI.

[1] https://twitter.com/j4/status/559842292597784576
[2] http://party.coop/lists/members-of-parliament/
[3] https://en.wikipedia.org/wiki/Co-operative_Party
[4] http://openelectoralcommission.org.uk/parties/PP53/labour-party/
[5] http://openelectoralcommission.org.uk/parties/PP119/co-operative-party/

**Comment by symroe** [comment]
My findings were form the Electoral Commission's Nomination Paper.  The note against the optional "description" field says: 

> A candidate supported by a certificate of authorisation signed by the Nominating Officer of a political party (or someone on their behalf) may use the party name or a description allowed by that certificate and registered with the Electoral Commission. A candidate may stand on behalf of two or more different parties and use a registered joint description if supported by certificate(s) of authorisation from each of the parties. Any candidate may alternatively use the description of ‘Independent’ (and/or ‘Annibynnol’ in Wales), or leave the description box blank.

**Comment by tfgg** [comment]
I just got a nice email (Tue, Mar 10, 2015 at 10:26 PM) from Jonathan Reynolds MP reminding us about this.

One additional option would be to have an optional field for the party description being used.

**Comment by mhl** [comment]
After some discussion last week, I think going for @tfgg's option 2 is probably the most pragmatic way to fix this - this depends on https://github.com/mysociety/yournextmp-popit/issues/314

**Comment by andylolz** [comment]
As an even quicker short-term fix, the joint description virtual parties could be added to data/all-parties-from-popit. This would mess up the stats, of course – but the candidate pages would at least be accurate.
