### ISSUE TITLE
Long strings in revision history on candidate pages break UI on mobile

### ISSUE THREAD

**Issue by edent** [mysociety/yournextmp-popit#172]
As a user viewing the page on a mobile device, I don't want to have to scroll horizontally to read the data.  I expect tabular data to fit in a single column where possible.

Currently, Webkit based browsers (Chrome and Opera) overflow the viewport, making horizontal scrolling necessary.  For example, on [Francis Maude](https://yournextmp.com/person/2551/francis-maude)'s page, it looks like this :
![maude webkit zoon](https://cloud.githubusercontent.com/assets/837136/5991956/0eddeffe-aa08-11e4-8589-ae340f9d46e5.png)
As you can see, the page starts in zoomed out mode. It doesn't wrap when zoomed in.

When viewed on a Gecko based browser (Firefox mobile), it looks like this : 
![maude firefox](https://cloud.githubusercontent.com/assets/837136/5991942/64e56658-aa07-11e4-938e-3541577950ec.png)

I *think* this can be solved by adding to the `table` element the following CSS.

    word-break: break-word;

I've only tested it on desktop, not mobile.
(Related to #146)

**Comment by mhl** [comment]
@edent Thank-you for the clear bug report and the suggested fix. I think this should be much improved by the new candidate page design in https://github.com/mysociety/yournextmp-popit/pull/159#issuecomment-72364334 (hopefully to be deployed tomorrow). I've tried it in Chromium's mobile emulation and Francis Maude's page looks like this:

![new-design-responsive](https://cloud.githubusercontent.com/assets/7907/5992726/5dab8ff4-aa2d-11e4-9418-ae2da08fac2c.png)

... and further down that page, the long links wrap OK:

![new-design-responsive-lower](https://cloud.githubusercontent.com/assets/7907/5992732/99f6aee4-aa2d-11e4-8481-bcc56fd8f705.png)

So I hope that will be OK once we deploy that change.

**Comment by edent** [comment]
Nifty! Looking forward to trying it out.

**Comment by mhl** [comment]
@edent Thanks - that's deployed now, so I'll close this - please let us know if there are any problems with the new design on mobile.

**Comment by edent** [comment]
There's still a problem on Chrome (Opera and FF are fine).  This time it's caused by long strings in the "versions" section.
![screenshot_2015-02-02-21-31-26](https://cloud.githubusercontent.com/assets/837136/6009622/4129adc4-ab23-11e4-88bc-d97951e50d7e.png)
(Again, F Maude.)
Should this be a new bug?

**Comment by mhl** [comment]
Ah, oh dear - I'll reopen this issue, in that case...
