### ISSUE TITLE
check that Scottish Green Party members are assigned to the right party

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#173]
There are probably other cases like this, but here's one to flag up anyway. The Green Party is a different registered party in Scotland (["Scottish Green Party"](https://yournextmp.popit.mysociety.org/organizations/party:130)) and in England and Wales (one of these two: https://yournextmp.popit.mysociety.org/organizations/party:63 and https://yournextmp.popit.mysociety.org/organizations/party:305 - both seem to have candidates associated with them, although more for the former)

We should check through all the people in Scottish constituencies who are associated with the Green Party and change them to the Scottish Green Party.

Note that this will only come up for parties regarded as the same party that have different registered parties for one of Scotland, England and Wales - the EC has a different registry for Northern Ireland already, and we only let users select parties from that registry for candidates in constituencies in Northern Ireland.

**Comment by andylolz** [comment]
I checked this with the following script:
https://gist.github.com/andylolz/61be99425dd3caf3d7ad

Found and fixed three instances ([Central Ayrshire](https://yournextmp.com/person/5169/veronika-tudhope), [East Lothian](https://yournextmp.com/person/5004/jason-rose), and [Dundee West](https://yournextmp.com/person/5763)).

**Comment by mhl** [comment]
@andylolz Nice! Thank-you :) I'll close this now.
