### ISSUE TITLE
Errors in 2010 data

### ISSUE THREAD

**Issue by sjorford** [mysociety/yournextmp-popit#182]
There are two candidates listed in the database as standing in 2010, that it seems actually didn't:

[Stroud](https://yournextmp.com/constituency/65858/stroud) - David Michael - Free Public Transport Party
[Stroud District Council](http://www.stroud.gov.uk/info/elections/Stroud_Constituency.pdf)
[Electoral Commission](http://www.electoralcommission.org.uk/find-information-by-subject/elections-and-referendums/past-elections-and-referendums/uk-general-elections/2010-uk-general-election-results/stroud)

[Ipswich](https://yournextmp.com/constituency/65925/ipswich) - Helen Bright - Liberal Party
[Ipswich Borough Council](https://www.ipswich.gov.uk/sites/www.ipswich.gov.uk/files/2010%20Parliamentary%20General%20Election%20Results.pdf)
[Electoral Commission](http://www.electoralcommission.org.uk/find-information-by-subject/elections-and-referendums/past-elections-and-referendums/uk-general-elections/2010-uk-general-election-results/ipswich?undefined=http%3A%2F%2Fwww.electoralcommission.org.uk%2Ffind-information-by-subject%2Felections-and-referendums%2Fpast-elections-and-referendums%2Fuk-general-elections%2F2010-uk-general-election-results%2Fipswich)

These seem to be the only two differences to the Electoral Commission database. Can these two candidacies be deleted?

**Comment by mhl** [comment]
Thank-you for finding those errors, I've deleted their 2010 candidacies. Also, I assume that you wrote a script to scrape and compare the results (including resolving with name differences) to find that out, which is great - is that online somewhere? (I quite understand if not! :))

**Comment by tfgg** [comment]
This is interesting, David Michael is actually in the Statement of Persons Nominated

http://www.stroud.gov.uk/info/elections/statement_member_parliament.pdf

but withdrew his nomination. We must have either not noticed the withdrawal, or seen an earlier nominations?

**Comment by mhl** [comment]
Thanks, @sjorford
