### ISSUE TITLE
Numbers don't add up on the https://yournextmp.com/numbers/ page

### ISSUE THREAD

**Issue by paullenz** [mysociety/yournextmp-popit#185]
Logically, I would expect the total number of candidates known to equal the number of candidates standing again + the number of new candidates

This would give me 2,740 (see screen shot) but the quoted number is 2,706

Are you perhaps double counting people who are standing again in a different constituency - they *are* standing again, but they are new to that constituency?

![screenshot 2015-02-03 20 15 25](https://cloud.githubusercontent.com/assets/909811/6028472/cbb5f22c-abe1-11e4-9f89-c6901f780129.png)

**Comment by sjorford** [comment]
It looks like the number of new candidates includes those standing again but for a new party.

**Comment by mhl** [comment]
The referenced pull request hopefully makes this a bit clearer - for example here's an example from my local mirror (which is a few days out of date, hence the lower numbers):

![new-numbers](https://cloud.githubusercontent.com/assets/7907/6041175/b7583d68-ac71-11e4-8772-b545949c23c7.png)

**Comment by mhl** [comment]
That new version's deployed now, so I'm closing this issue
