### ISSUE TITLE
Add OpenGraph and twitter card tags

### ISSUE THREAD

**Issue by symroe** [mysociety/yournextmp-popit#187]
As requested by Owen, something like the following would make facebook shares much nicer:

`<meta property="og:image" content="http://ia.media-imdb.com/images/rock.jpg" />`

Also, twitter 'card' tags would make twitter shares nicer.

**Comment by owenblacker** [comment]
* [Facebook Open Graph metadata format](http://ogp.me)
* [Twitter Card metadata format](https://dev.twitter.com/cards/types/summary)

**Comment by mhl** [comment]
@frabcus suggested this primer for adding basic OG and Twitter Card tags:

* http://moz.com/blog/meta-data-templates-123
