### ISSUE TITLE
make photo upload form clearer

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#228]
The photo upload form is already proving to be a bit confusing:

![photo-upload](https://cloud.githubusercontent.com/assets/7907/6433111/f804baa8-c05d-11e4-875e-14fb08cb82a2.png)

The two checkboxes are really mutually exclusive, so should be radio buttons instead. After some discussion with @andylolz I think it might be better as 4 radio buttons:

* This photograph is free of copyright restrictions (e.g. in the public domain)
* I own copyright of this photo and I assign the copyright to Democracy Club in return for it included in YourNextMP
* This is the candidate's public profile picture from social media (e.g. Twitter or Facebook)
* Other

... and then the "Here is my justification for why this photo may be reasonably used on the website, including the source URL:" text area.

**Comment by zarino** [comment]
I was just about to suggest radio buttons!

I assume, if we go with the four you've suggested, then the text box would only be shown if you select "Other"? (Since the previous three choices don't need a justification?)

**Comment by andylolz** [comment]
I’d say the text box should be a required field independent of the radio buttons – like the source box on the person edit form. I don’t know if it’s sufficient for someone to say “this is public domain” – I’d like to see some evidence of that. The text box is a good place for them to do that.

**Comment by mhl** [comment]
Yeah, this has only been deployed for about 12 hours, and already it's clear that:
* People misunderstand "public domain"
* The things they've put in the "justification for use" box have been generally helpful
