### ISSUE TITLE
Refresh party list from Electoral Commission

### ISSUE THREAD

**Issue by sjorford** [mysociety/yournextmp-popit#239]
Can the list of parties be refreshed again - in particular I've added a few candidates from Cista (Cannabis is Safer than Alcohol) which isn't in the YourNextMP list yet.

**Comment by mhl** [comment]
@symroe I can't see this one in the http://openelectoralcommission.org.uk/parties/ - could you possibly re-run the scaper and I'll update YNMP from that when it's complete?

**Comment by andylolz** [comment]
Definitely in there now: http://openelectoralcommission.org.uk/parties/PP2552/cannabis-is-safer-than-alcohol/

**Comment by symroe** [comment]
@mhl Odd that you couldn't see it – I haven't updated the scraper in between yours and @andylolz's comments!

**Comment by mhl** [comment]
Hm, some kind of failure to use ctrl-F correctly, I suppose. I've updated the list now.

@sjorford You should be able to select "Cannabis Is Safer Than Alcohol" from the party list now. Thanks for your bug report.
