### ISSUE TITLE
Allow editors to specify birth year for a candidate (rather than full date of birth)

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextmp-popit#246]
@mhl says:

> PopIt can just have a year (or year + month) in the date of birth field, but we're not allowing that to be entered in YourNextMP at the moment. It might be better to allow that and then say to people who don't want to give their full date of birth “just enter the year and month then”.

I tried entering just the year of birth via the YNMP PopIt instance, but it failed to save with no error message shown.

**Comment by andylolz** [comment]
Looks like @dracos made a handy thing for doing this:
https://github.com/dracos/django-date-extensions

Not sure if this was what you meant, Mark, but I propose allowing YYYY, but not advertising it as such (i.e. leave the label as is).

Lots of emails from candidates contain just year of birth, so it would be useful to add it (I’m not able to do it through the PopIt interface either, because mysociety/popit#789.)

**Comment by nealeu** [comment]
Given that date of birth does figure in security questions, I think requiring and publishing the full date of birth is not appropriate.  Age on election day would be sufficient.

**Comment by gerv** [comment]
I have a list of candidates sent to me from one party, and many of the entries contain only a year of birth. As things stand, I can't enter that information.

**Comment by gerv** [comment]
And, in fact, the argument above about making people's full DOB public is a good one. I do have some full DOBs, but I'm wary of putting them into the form without express candidate permission. So again, a YOB option would be a good one.
