### ISSUE TITLE
Use the most recently added photo

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextmp-popit#250]
We currently use the earliest uploaded photo, rather than the most recent. The workaround when adding a new photo involves deleting the previous photo (which incidentally causes PopIt to crash – see: mysociety/popit#783).

This is particularly a problem with the new moderation queue, because it’s easy not to realise that the candidate already has a photo. If this is missed, the new photo won’t be used. One workaround would be to flag to the moderator that a candidate already has a photo e.g. by showing it.

**Comment by mhl** [comment]
Ideally we would fix this with: https://github.com/mysociety/popit/issues/796

**Comment by andylolz** [comment]
Perfect!

**Comment by chrismytton** [comment]
https://github.com/mysociety/popit/issues/796 has now been fixed by https://github.com/mysociety/popit-api/pull/134, so this should now be relatively simple to fix.

**Comment by andylolz** [comment]
Ace! Will the fix include rearranging the currently held images, to do one of these:

```
images = [images[-1]] + images[:-1] if len(images) > 1 else images
```

…or is that likely to cause more problems than it solves?

**Comment by chrismytton** [comment]
@andylolz I think that could potentially cause more problems and other instances might now want that change. So probably something that YNMP will need to do externally if required.

**Comment by andylolz** [comment]
@chrismytton sorry yeah – that’s what I mean. A one off job for YNMP (sorry I wasn’t explicit – this issue is on YNMP repo, but appreciate you’re jumping about between several!)

Specifically for YNMP – it’s still possible this might cause more problems… Based on your advice on reviewing photos where a worse one already exists (“leave it for now”) my guess is you wouldn’t be keen on doing this, @mhl?

**Comment by chrismytton** [comment]
@andylolz Ha, yes you're right, I'm totally getting my repos muddled up!
