### ISSUE TITLE
Gross offence over gender option

### ISSUE THREAD

**Issue by jonathanbishop** [mysociety/yournextmp-popit#251]
i find it grossly offensive that it is using the classification of gender rather than sex. Gender stereotyping in terms of whether someone is male or female is immoral and puts people in society who don't fit into either the male or female categories at a disadvantage. As an anthropologist and neuro-economist it is my view that any use of gender should be based on whether a person is autistic, empathic, demotic, psychotic, neurotic or a combination of these, as these are based on neurological categories and not society imposed ones. On that basis the system should ask for ones sex and not ones gender as sex is a protected characteristic in the Equality Act 2010, whereas gender is not. I have an XY chromosome, which makes me a Man. Anything about me which is male is society imposed and not neuro-genetic!

**Comment by mhl** [comment]
We see that a volunteer changed your entry in the free text gender field from "Man (Sex)" to "male" - this has now been reverted back to what you, as the candidate, chose the value to be: https://yournextmp.com/person/5769/dzon Sorry about that.

On the broader issue, I'm afraid we're going to keep the field name as "Gender" with a free text field, as this is widely considered to be best practice in collecting this demographic information.
