### ISSUE TITLE
"Candidates per party" is broken

### ISSUE THREAD

**Issue by gerv** [mysociety/yournextmp-popit#258]
https://yournextmp.com/numbers/parties is linked from https://yournextmp.com/numbers/ but gives a 500 Server Error.

Gerv

**Comment by mhl** [comment]
Thanks for reporting that - it's fixed now.

**Comment by gerv** [comment]
Broken again?

**Comment by mhl** [comment]
sigh, yes, sorry - fixed properly this time...
