### ISSUE TITLE
"Parties" totals are broken

### ISSUE THREAD

**Issue by gerv** [mysociety/yournextmp-popit#260]
On https://yournextmp.com/numbers/parties , it says there are 3 candidates for "Christian Party "Proclaiming Christ's Lordship". However, viewing the list reveals significantly more than 3 candidates.

There seem to be more than 3 standing in 2015, but part of the problem is people like e.g. Edward Strike, who stood for this party in 2010 but is standing for UKIP in 2015.

Gerv

**Comment by dracos** [comment]
Also there are two "Christian Party "Proclaiming Christ's Lordship" in the list (one with 5, one with 3), the URLs differ but the contents of the page appear to be the same (and with the issue of this ticket).

**Comment by gerv** [comment]
Yes. 3 candidates in one entry, 5 in the other, and 2 of the 10 candidates on the generated page are actually not standing for this party (but did so previously). They are Clive Morrison and Edward Strike.

Gerv

**Comment by mhl** [comment]
I think all these issues are resolved now.
