### ISSUE TITLE
Unable to delete photo

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextmp-popit#266]
I’ve uploaded a new photo for this candidate, but I’m unable to delete the current photo:
https://yournextmp.popit.mysociety.org/persons/4178

**Comment by mhl** [comment]
I'm afraid that's a side-effect of me messing up the images earlier; there's a temporary fix in place until Monday, then I hope we can fix it properly and then you'll be able to delete images again.

**Comment by andylolz** [comment]
Cool. Thanks!

**Comment by mhl** [comment]
@andylolz I think this should work now, if you want to give it another try.

**Comment by andylolz** [comment]
It did! The image I uploaded wasn’t there (I expected it to be the next in the list) but that’s fine – I uploaded it again.

Thanks!
