### ISSUE TITLE
Colours of candidate photos broken on upload

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextmp-popit#288]
e.g. https://yournextmp.com/person/6909

**Comment by mhl** [comment]
In case anyone has time to look into this (I won't today) here's a link to [the original uploaded image](https://yournextmp.com/media/queued-images/2015/03/23/lucyhall.png) and the PIL code that does the cropping and resizing is here:

* https://github.com/mysociety/yournextmp-popit/blob/master/moderation_queue/views.py#L171-L177

**Comment by lizconlan** [comment]
Hmm, it appears that this isn't a problem with the moderation queue code after all this is "just" cropping the image and it's resizing that can cause the gamma settings to change in an unhelpful way (frighteningly detailed explanation here if anyone fancies a long read on background: http://www.4p8.com/eric.brasseur/gamma.html#formulas).

So this is either a problem with the image-proxy code (as that's where the resizing takes place) or with the version of imagemagick (or associated library) installed on the server.

**Comment by mhl** [comment]
Affected people include:

* https://yournextmp.com/person/6909/lucy-hall
* https://yournextmp.com/person/7242/arthur-price

... and the photos we've been emailed by https://yournextmp.com/person/7325/helen-spiby-vann
