### ISSUE TITLE
latest versions of chrome show the yellow warning triangle for YourNextMP's certificate

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#293]
Recent versions of Chrome have started to show a yellow warning triangle for https://yournextmp.com to indicate some security problems; this is about the certificate chain using SHA-1 hashes at some point, which are considered to be subject to collision attacks these days. (See https://www.ssllabs.com/ssltest/analyze.html?d=yournextmp.com&hideResults=on for details.)

Google's blog post about this change is here: http://googleonlinesecurity.blogspot.co.uk/2014/09/gradually-sunsetting-sha-1.html

@symroe - since you bought the certificate, could you investigate getting a new certificate from them without that weakness? (I guess this'll be an FAQ for them by now.)

Thanks to @dracos initially and @struan pointing this out.

**Comment by symroe** [comment]
Regenerated and deployed – seems to be fixed now
