### ISSUE TITLE
Photo upload page should say if there's already one in the queue

### ISSUE THREAD

**Issue by gerv** [mysociety/yournextmp-popit#297]
If there's already a photo in the review queue for a candidate, the photo upload page should say so, so that people don't spend time searching for information which has already been provided.

For bonus points, if a photo is disapproved, it would be useful to say that, and why, so that the same photo is not uploaded again. But the point above is the most important one.

Gerv

**Comment by mhl** [comment]
Thanks for the suggestion, @gerv - I've implemented the main suggestion; it's not very pretty (this page hasn't had any design time really) but hopefully will improve the situation:

![photo-already-uploaded](https://cloud.githubusercontent.com/assets/7907/6996308/54b082a2-db78-11e4-8349-b093bd3b5431.png)

(n.b. the red "1" at the top would only be seen by photo moderators; that just indicates the number of photos in the queue.)

I'm not sure about the second suggestion - if a photo is rejected, the uploading user gets an email explaining why, which I'd have hoped is sufficient. (That said, some people do then carry to upload exactly the same photo without apparently having read the reason it was rejected - I'm not sure those people would be helped by having it on the photo upload page too.)

**Comment by gerv** [comment]
Looks good :-)
