### ISSUE TITLE
on party pages, don't list every constituency for smaller parties

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#305]
Perhaps if a party is field candidates in less than a third of the constituencies in a region of the UK, don't list *all* constituencies in that region - this would make pages like: https://yournextmp.com/party/party%3A54/the-liberal-party more helpful

**Comment by dracos** [comment]
This looks to be done?

**Comment by mhl** [comment]
Yes, thanks - done in c7c4cd11b56d668eeee9b0
