### ISSUE TITLE
Once candidates confirmed (today?) remove `candidates__previous` and `candidates__not-standing` divs from constituency page

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextmp-popit#309]
I guess [this](https://github.com/mysociety/yournextmp-popit/blob/master/candidates/templates/candidates/constituency.html#L65-L67) and [all of this](https://github.com/mysociety/yournextmp-popit/blob/master/candidates/templates/candidates/constituency.html#L71-L143) can be commented out/removed in the next few days?

**Comment by mhl** [comment]
What we did in the end was to not show those divs any more once the constituency is locked, and they're all locked now, so I'll close this.
