### ISSUE TITLE
import party descriptions into PopIt

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#314]
For many of the registered parties there are descriptions, from which the candidate can pick some text to appear on the ballot paper. It would be useful to have these available in PopIt, so that, for example, we can pick each candidate's chosen description to show on the site. This means changing the `candidates_update_popit_parties_from_ec_data` command to add a descriptions array to the organization from the OpenElectoralCommission data. (The OEC scraper seems to be a bit broken at the moment—it's missing some parties—but this should bring in descriptions for most parties.

**Comment by andylolz** [comment]
In the EC API data, the relevant property is `PartyDescriptions`. It’s either `null`, or an empty list, or a list of objects of the form:

```
{
    Description: "…",
    Translation: "…",
    RegulatedEntityId: some ID number
}
```

Sample data: http://pefonline.electoralcommission.org.uk/api/search/Registrations?start=10&rows=10&et=pp&et=ppm&register=gb&register=ni&regStatus=registered&regStatus=deregistered&regStatus=lapsed

**Comment by mhl** [comment]
Work in progress in the the [wip-add-descriptions](https://github.com/mysociety/yournextmp-popit/tree/wip-add-descriptions) branch - the change to `candidates_update_popit_parties_from_ec_data` is db231b130e55f45e
