### ISSUE TITLE
plan out migration to YNMP-read / YNMP-write

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#322]
@symroe and @tfgg have been working on ["YourNextMP-read"](https://github.com/DemocracyClub/YourNextMP-Read), a static site with the same style and data as YourNextMP but with more of a focus on providing information for people finding out about their candidates than trying to attract those who want to help with crowd-sourcing; the editing interface would move to edit.yournextmp.com. (For example, here's [a constituency page from YNMP-read](http://ynmp.democracyclub.org.uk/constituency/66060/oxford-east/).) As I understand it, DemocracyClub are planning to host YNMP-read. Here's a draft list of things to do, almost certainly with mistakes or omissions:

- [x] Get a certificate for edit.yournextmp.com or a wildcard certificate for *.yournextmp.com
- [x] Lower the DNS TTL for yournextmp.com (@Flupsy took it down to an hour)
- [x] Point the DNS for edit.yournextmp.com to pluto
- [x] Add edit.yournextmp.com as a ServerAlias for the existing sites
- [x] Tell Google Analytics that edit.yournextmp.com and yournextmp.com should be considered the same site - the snippets on both sites will need to be changed as described here: https://support.google.com/analytics/answer/1034342?hl=en **Update** There's a PR for yournextmp-popit here: https://github.com/mysociety/yournextmp-popit/pull/332 and one for YourNextMP-Read here: https://github.com/DemocracyClub/YourNextMP-Read/pull/41
- [x] Update the sites table for the existing site to make the site's domain edit.yournextmp.com
- [x] Change django's `ALLOWED_HOSTS` setting to include with `edit.yournextmp.com` or `*.yournextmp.com`.
- [x] Ensure that the YNMP-read is running, and has the yournextmp.com certificate and key installed
- [x] Establish whether there's a plan to have any "edit" links from YNMP-read to edit.yournextmp.com - candidates are still actively editing their profiles and this doesn't seem to be dropping off, so it would be a shame it if was no longer clear to people how to do this
- [ ] <del>Conversely, make sure that after editing on edit.yournextmp.com you get redirected to YNMP-read</del>
- [x] Update the DNS for yournextmp.com to point to YNMP-read
- [x] Quickly afterwards, change the redirection for the old YNMP crowdsourcing site so that it redirects aliased names to edit.yournextmp.com, not yournextmp.com.
- [x] Change social logins (only needed for edit.yournextmp.com) so that they have the right domain in their callback URLs
- [ ] Raise the DNS TTL back to normal for yournextmp.com

Random notes of things to be careful of:

* The site is getting a lot of traffic at the moment, so we need to make sure that this migration will happen without downtime 
* We'll have to buy another certificate for edit.yournextmp.com or perhaps get a wildcard certificate
* Make sure we still use the same Google Analytics identifier for both sites so we have continuity of analytics
* Check that social logins still work for edit.yournextmp.com - this means updating the callback URLs for Twitter, Google and Facebook login

**Comment by symroe** [comment]
> Get a certificate for edit.yournextmp.com or a wildcard certificate for *.yournextmp.com

The wildcard from gandi.net costs abotu 5x a single cert.  I think a single one would be best for now.  I will get this today.

> Establish whether there's a plan to have any "edit" links from YNMP-read to edit.yournextmp.com - candidates are still actively editing their profiles and this doesn't seem to be dropping off, so it would be a shame it if was no longer clear to people how to do this

https://github.com/DemocracyClub/YourNextMP-Read/issues/24

> Conversely, make sure that after editing on edit.yournextmp.com you get redirected to YNMP-read

This might be confusing for some people, as the read site will only update every hour or so.  We should think about how best to manage that.


Another point, I expect we'll need to change django's `ALLOWED_HOSTS` setting to include with `edit.yournextmp.com` or `*.yournextmp.com`.

**Comment by symroe** [comment]
SSL ordered, waiting for verification process.

**Comment by mhl** [comment]
This is all done now, except raising the DNS TTL, so I'm closing the issue. @Flupsy - I'm not sure if you want to raise it? Looking in the history of the DNS zonefile I couldn't find the commit where you lowered it.

**Comment by Flupsy** [comment]
Not bothered, an hour is our default so I'll just leave it at that.
