### ISSUE TITLE
Post Nominal Field maxlength Too Short

### ISSUE THREAD

**Issue by edent** [mysociety/yournextmp-popit#338]
[Professor Andrew Knight](http://www.animalwelfareparty.org/2015/04/09/animal-welfare-party-announces-four-candidates-2015-uk-general-election/) has the following post nominals - "BSc (Vet Biol), BVMS, CertAW, DipECAWBM (AWSEL), PhD, MRCVS, SFHEA"

That's 66 characters of text.  The `maxlength` of the field is (an entirely reasonable) 64 characters.

https://github.com/mysociety/yournextmp-popit/blob/51d6ae7a99ce1dfe8b6da3d9ec3b53ecb715ce71/candidates/forms.py#L90

I'm not sure if that's a database restriction, or simply a concerted effort to denigrate the intelligentsia⸮

Probably not a high priority fix - but might be worth considering which other fields are arbitrarily short.

**Comment by jonathanbishop** [comment]
I have experience this problem also. I've had to limit my post-nominals to my degrees and fellowships, without the institutions named. I have a lot more memberships to add. Having post-nominals does not indicate any level of intelligence, and those who think they do have confidence issues. For me I collect them no differently to how some people collect stamps, or others collect figures on their bank balance. I would prefer the post-nominals on this website to be below the candidate name and not after it. The candidate name has already been agreed to be what is on the ballot paper, so maybe that field should be locked after the close of nominations.
