### ISSUE TITLE
AR: get a list of MapIt IDs (or other official IDs) for provinces, departments and municipalities

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#352]
Global MapIt seems to have quite good data for Argentina. The O04 type has provinces and the autonomous city of Buenos Aires. I've made a [Google spreadsheet of Global MapIt links for each of those](https://docs.google.com/a/mysociety.org/spreadsheets/d/1SkhMsEZYECTHc7Lq_SlcO4lbKlHnM6z-NuwDkrLum-Y/edit#gid=0).

From those we should find any departmento (or partido in Buenos Aires province) contained within them (of type O05). Municipalities are of type O07, and similary could be found from a simple script. Then we can examine which regions are missing from the resulting dataset.

If there are more official sources of shapefiles that we could use (with official IDs) we could set up a custom MapIt for those too.

**Comment by martinszy** [comment]
Here's the official shapefiles:
http://www.ign.gob.ar/NuestasActividades/sigign#descarga

For the first release, only national an provincial-level candidates are going to be considered. Municipalities and departments are of secondary priority at this time.

**Comment by mhl** [comment]
@martinszy: That's very helpful, thank-you. Have you already got a MapIt instance with these boundaries? I'm happy to write an import script for them.

**Comment by mhl** [comment]
Here's a pull request with an import script for provinces and deparatments:

* https://github.com/mysociety/mapit/pull/188

The shapefiles for departments have a numeric ID for each in the `cod_depto` field (e.g. Concordia is 30015), but there's no obvious official code for provinces in the shapefiles. (Actually for some reason the department codes haven't been imported, but I'm sure that's easy to fix.)

**Comment by martinszy** [comment]
Here's a table showing which provinces are electing which thing on the primaries:
https://docs.google.com/document/d/11GR66gN4e34a3HlVzV8l2-RrhbBihhdj7GAOV7fND1o/edit#heading=h.ooju14sfjio

Note: We have pre-candidates, who if win, will become candidates. This are primaries.

**Comment by mhl** [comment]
@martinszy One thing I forgot to ask about - do you know what the license is for the official shapefile data?
