### ISSUE TITLE
AR: create a popit with all the types of posts with areas

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#355]
Depends on https://github.com/mysociety/yournextmp-popit/issues/352

This should be a Django management command to create an empty PopIt for the 2015 Argentine elections, similar to the old and deprecated https://github.com/mysociety/yournextmp-popit/blob/c34d6474aa40fb16f063438b0527514c82529623/candidates/management/commands/candidates_create_popit.py

**Comment by martinszy** [comment]
This is a list of parties we have in a spreadsheet: 
https://docs.google.com/spreadsheets/d/11djkCWXl9RtXvsh-Z1gDL7jgJ8-HYTaprxksKAbyOF0/edit#gid=0

I will turn in into JSON like this one:
https://github.com/mysociety/yournextmp-popit/blob/master/data/all-parties-from-popit.json

**Comment by martinszy** [comment]
Sent the national party list. Please check.

**Comment by mhl** [comment]
There's both a staging PopIt instance and the live one here:

* https://ynr-argentina.popit.mysociety.org/

Dealing with the per-province lists of parties is covered by this issue: https://github.com/mysociety/yournextmp-popit/issues/385
