### ISSUE TITLE
Markup error

### ISSUE THREAD

**Issue by winghouchan** [mysociety/yournextmp-popit#362]
Howdy!

There is an error in the markup for https://yournextmp.com/

The ```head``` has been opened twice and closed twice. Also there are two ```title``` tags.

See the image attached for the code and the pinpointed errors.

![screen-shot-2015-05-01-at-13 31 05](https://cloud.githubusercontent.com/assets/6061021/7430172/d14cba54-f006-11e4-8310-70b126608d7e.jpg)

**Comment by andylolz** [comment]
Thanks, winghouchan! The repo for that one is here:
https://github.com/DemocracyClub/YourNextMP-Read

I spotted the same error, but it would still be super useful if you could create the issue on that repo!

**Comment by winghouchan** [comment]
Ahhh, okay. I just clicked the issue tracker link on the bottom of the https://yournextmp.com/ page.

Will create an issue for this on that repo :smiley:

Closed and moved to: https://github.com/DemocracyClub/YourNextMP-Read/issues/112
