### ISSUE TITLE
Cannot delete Twitter usernames

### ISSUE THREAD

**Issue by ianroberts** [mysociety/yournextmp-popit#365]
The Twitter username listed against Peter Bush (https://yournextmp.com/person/6754/) is no longer active, so I tried to edit his entry to remove it but the change was ignored - it did save a new version with my description of the change, but did not actually change the `twitter_username` property.

**Comment by andylolz** [comment]
I just gave it a go and experienced the same thing. I wonder if this is related to #351?

**Comment by mhl** [comment]
Thanks for reporting this - it should be fixed now, if you'd like to try again?

**Comment by ianroberts** [comment]
Confirmed, I have just deleted the dead username successfully.
