### ISSUE TITLE
CSV download is broken

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/yournextmp-popit#370]
https://edit.yournextmp.com/media/candidates.csv is currently returning lines like this:
```
Richard Taylor,3237,National Health Action Party,Wyre Forest,66078,http://mapit.mysociety.org/area/66078,E14001058,DrRTaylorMBE,,http://nhap.org/dr-richard-taylor/,male,,RTT7601@gmail.com,http://www.healthconcern.org.uk/,http://en.wikipedia.org/wiki/Richard_Taylor_%28British_politician%29,1934-07-07,uk.org.publicwhip/person/11275,http://www.theyworkforyou.com/mp/11275,Dr,MBE FRCP,PP1931,,False,http://yournextmp.popit.mysociety.org/persons/3237/image/5535730a367dc5383f552cd3,http://yournextmp.popit.mysociety.org/image-proxy/http%3A%2F%2Fyournextmp.popit.mysociety.org%2Fpersons%2F3237%2Fimage%2F5535730a367dc5383f552cd3/{width}/{height}.{extension},other,andylolz,"License: Creative Commons Attribution-Share Alike 3.0 Unported license
Source: https://en.wikipedia.org/wiki/File:Richard_Taylor_MP.JPG
Author: Original uploader was Rathfelder at en.wikipedia"
```

**Comment by dracos** [comment]
Newlines within quote marks are allowed; python's `cdv` seems to handle it fine, for example.

**Comment by tmtmtmtm** [comment]
The parser I'm using does too, so that mustn't have been the problem. I reverted the file with all the new columns yesterday, but today a fresh download is working fine, so I'm not sure what went wrong yesterday. Closing for now; will re-open with a more detailed error message if it returns.

**Comment by mhl** [comment]
There are archives of old CSV files here: https://edit.yournextmp.com/media/csv-archives/ in case you want to try to reproduce this.
