### ISSUE TITLE
fix the h1 of /areas pages

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#389]
These are a bit silly at the moment:

![bad-titles](https://cloud.githubusercontent.com/assets/7907/8082206/6e2b5e8a-0f73-11e5-8736-5475e8f67b34.png)

They should probably join the names of the areas, not the posts associated with those areas.

**Comment by dracos** [comment]
"Joining" will be a translation problem, regarding of what you're joining :)
