### ISSUE TITLE
Create button for "Thanks" page allowing user to take further actions

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextmp-popit#405]
Once the user has finished filling a candidate, to allow them to go directly to a fill a new candidate for the same election, so this will be a button on the thanks page after edition.
- Add new candidate for the same election
- Edit this candidate again
- Look for other elections to add candidates (links to the page created by #404 )

**Comment by mhl** [comment]
I've made [a pull request with this](https://github.com/mysociety/yournextmp-popit/pull/418) - @zarino, would you want to change the styling for this?

![calls-to-action-after-adding](https://cloud.githubusercontent.com/assets/7907/8475946/3e04fc50-20b4-11e5-90e8-2099e450eee1.png)

**Comment by zarino** [comment]
Hopefully once https://github.com/mysociety/yournextmp-popit/pull/420 has been merged, that hot pink will be toned down to something more legible.

Other than that, I'd probably remove the extra padding after the list. But I don't think it's urgent.
