### ISSUE TITLE
Add a new candidate button doesn't work

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextmp-popit#408]
The button to add a new candidate does nothing currently

http://argentina.ynr.staging.mysociety.org/election/senadores-argentina-paso-2015/post/sen-prim-3/candidato-a-senador-nacional-por-catamarca as an example.

**Comment by mhl** [comment]
If you're not signed in, this will be: https://github.com/mysociety/yournextmp-popit/issues/388
