### ISSUE TITLE
Add a "this person won" button

### ISSUE THREAD

**Issue by dracos** [mysociety/yournextmp-popit#61]
It would be good, in a lovely ideal world, for there to be a button that could update the person data store that TheyWorkForYou is using and prompt an update of data on TheyWorkForYou. On election night, some authenticated person could click this button for each constituency as results came in. They would not have to manually update an XML file and run a Perl script 650 times. Who would do that? Even if they get some of the results before the PA.

Currently, that would be something that edited `all-members-2010.xml` (or a new `2015` file I guess) and prompted a run of a changed/updated/renamed `xml2db-2010.pl`. It could theoretically, if time were available, be an update of some Popolo person data (potentially in PopIt) and a run of an update script (that would have been changed already to deal with those changes).

Historical note that can be ignored, but I don't think I've written this anywhere before:

For the 2005 general election, I was at a conference in Canada (that's a sad aside as to how I saw nothing of Vancouver but the airport and the hotel, and of course the lovely view across the water to the mountains from the hotel), and so the time difference was quite handy for updating people at the election. I can't be bothered to dig into the CVS or SVN archaeology as to how it was updated, but it was.

Between the 2005 and 2010 general election, TheyWorkForYou gained historical MPs back to the start of Hansard (18mumble mumble) based on some work and open data from Parliament. The `all-members.xml` file grew to be rather larger than it had hitherto been.

This larger file took much longer to parse/import, which was never really a concern for something that was only run for a MP change or similar. At the time of the 2010 general election, I wanted to have TheyWorkForYou update with election results as quickly as possible (see aforementioned beating the PA feed), so <a href="https://github.com/mysociety/parlparse/commit/332f736909774af5429e47378ba5e0192e29b6c5">made a 'temporary' separate XML file</a> that could be edited and loaded in separately more quickly. This file has of course persisted since then.

**Comment by andylolz** [comment]
I really like this idea. (Related: I’d really like to see “Your Next MP is…” on each YourNextMP constituency page on election night.)

> some authenticated person could click this button for each constituency as results came in

Yes… I guess it might be necessary for them to be trusted.

>  I think that's my election night plan sorted

Amazing! We have a winner! :rocket:

**Comment by mhl** [comment]
Things to do:

- [ ] add a group called something like "Election Results Collector"
- [ ] add a button (only for people in that group) for "This person won!", and, if there's on parlparse ID for that person, an optional field for parlparse ID, which the user should fill in if they find that that person was previously an MLA or an MSP, for example
- [ ] on clicking, that should set the parlparse ID and create a membership of the post with role "Member" and organization_id set to whatever the House of Commons's ID is
- [ ] update the CSV export to add an "Elected" column which will be either empty (no results yet), True or False

**Comment by MyfanwyNixon** [comment]
I have written a draft blog post about this process, and I'd be glad if it could be fact-checked please. It's actually rather light on technical detail and (personally) I think that's fine for the majority of our readers; devs, you might want to write a more tecchie post later on? 

https://blogs.mysociety.org/mysociety/?p=23991&preview=true

**Comment by wrightmartin** [comment]
I've quickly thrown together changes to YNMP's public facing front-end post election. 

This is mainly to give us some discussion points, so be sure to let loose with your feedback :)

### Constituency page
- Add a notification style message to the top with the winner (wording needs addressing) and give some 'what can I do next' context. I've only added TWFY here, but it could be anything you want.

I've kept the rest of the page as is, but I wonder should we also indicate on their box in the list somehow?

![ynmp-elected-constituency](https://cloud.githubusercontent.com/assets/2292925/7428234/a266774c-efe4-11e4-82a4-16c2ba3c74a9.png)

### Candidate page
- Change subtitle to "Member of Parliament for..."
- Change first paragraph of body to 'elected', rather than candidate
- Add link to TWFY in RH column

Looking at this now maybe it could be a little less subtle? Thoughts?

![ynmp-elected-candidate](https://cloud.githubusercontent.com/assets/2292925/7428244/ea336a44-efe4-11e4-9d14-8d9ea0576941.png)

Let me know your thoughts and any further changes

**Comment by wrightmartin** [comment]
> maybe I'd go to town on the candidate page – a bigger message saying "This candidate won in the 2015 election. Show the other candidates.
– @zarino

**Comment by MyfanwyNixon** [comment]
I understand the branding impetus behind "Your next MP is", but I think it's clearer/more impactful if it says "Your new MP is".

Maybe "The election is over! The votes have been counted! Your new MP is..."

On the box, how about a "winner" or "elected" ribbon or a rosette? This could also go on the candidate page. 

And then maybe something on the non-winners' pages to show that they were unsuccessful?

Across the other areas of the site, eg the CV upload, the past tense will now feel more appropriate than the present perfect (ie "no-one sent a CV" instead of "no-one has sent".

**Comment by wrightmartin** [comment]
> I understand the branding impetus behind "Your next MP is", but I think it's clearer/more impactful if it says "Your new MP is".

Of all the people myf I thought you'd love this bit :) Fancy penning something?

> And then maybe something on the non-winners' pages to show that they were unsuccessful?

Good point!

> On the box, how about a "winner" or "elected" ribbon or a rosette? This could also go on the candidate page. 

What do others think about this? I wasn't sure if it fits the general aesthetic of YNMP?

> Across the other areas of the site, eg the CV upload, the past tense will now feel more appropriate than the present perfect (ie "no-one sent a CV" instead of "no-one has sent".

Potentially a big job - but yeah, I assume the site will be kept online in its current state for archival purposes

**Comment by zarino** [comment]
![winner](https://cloud.githubusercontent.com/assets/739624/7428358/3b769d16-efe7-11e4-80eb-24e71e77e9cc.png)

If the winning MP's a new one, their TWFY profile page will be mostly empty, with [just a box to subscribe to email updates](https://github.com/mysociety/theyworkforyou/issues/703). Could we save people a click, by doing something like…?

```python
# pseudo-code
if candidate.won_in_2015 and candidate.won_in_2010:
  print '<a href="…">Show this candidate’s voting history on TheyWorkForYou.com</a>'
else:
  print '<a href="…">Get notified when this candidate next acts in Parliament</a>'
```

Or even putting the form *inline* on YNMP and posting to the TWFY email subscription endpoint directly?

**Comment by wrightmartin** [comment]
Here's updated designs

### Losing candidate
- Show a message with a link to the constituency

![ynmp-unelected-candidate](https://cloud.githubusercontent.com/assets/2292925/7430830/dabcde30-f00f-11e4-925d-60c20d6ed6a6.png)

### Elected candidate
- Added a announcement with a rosette

![ynmp-elected-candidate](https://cloud.githubusercontent.com/assets/2292925/7430831/dabd9424-f00f-11e4-98c6-97b21af4850f.png)

### Constituency
- Change wording based on Myf's feedback, added subscribe link

![ynmp-elected-constituency](https://cloud.githubusercontent.com/assets/2292925/7430832/db13d2d0-f00f-11e4-99b5-c2c619fa4f99.png)

**Comment by MyfanwyNixon** [comment]
:+1: Is the 'w' for 'winner'? Could potentially be confusing, I guess.

**Comment by zarino** [comment]
What's the "W" in the rosette stand for? "Winner"? How about a "#1" instead?

And "Subscribe to Laura Davies updates on TheyWorkForYou.com &rarr;" is a bit long for a call to action!

**Comment by MyfanwyNixon** [comment]
Assuming the LH call to action actually meant to say "View Laura Davies on TWFY.com" they'll both be quite long. A line break before 'on' might help. 

Although, it's hard to summarise the benefit in one short line like this: I'm not at all sure anyone will subscribe on such little information. Maybe 'Get an email every time Laura Davies speaks'?

Also - any value in 'write to your new MP now' and a link to WTT? I'm not sure when WTT will be up-to-date enough.

**Comment by wrightmartin** [comment]
Good feedback, here's the candidate page again with some changes

![ynmp-elected-candidate](https://cloud.githubusercontent.com/assets/2292925/7431106/3663f5f4-f013-11e4-9d1f-911411cd190b.png)

**Comment by zarino** [comment]
Sorry to pester, but I don't get the benefit of "Laura Davies on TheyWorkForYou.com" – why would I click that?

If we *know* that her page on TWFY shows her voting history, then surely a more attractive link would read "Laura Davies' voting history in Parliament".

If she's a new MP with no voting history, though, as I said above, I probably wouldn't even link to TWFY. It won't benefit people at all. Better, in that case, to prioritise the "Get notified when Laura Davies speaks in Parliament" call to action.

**Comment by wrightmartin** [comment]
@zarino good points, my thoughts:

Two things

- Getting a TWFY profile is kinda cool, proves you're really in parliament etc, 
- Promotes TWFY as the graduating step for YNMP users too, so there's no data there, so what? Look how useful it will be when there is data there.

**Comment by JoeMitchell** [comment]
Looks cool! I agree that the CTA should be to 'Get an email when Laura speaks in Parliament' - cos traffic is likely to disappear before Laura ever makes a vote :)

**Comment by mhl** [comment]
One thing we won't easily have (at the moment) is the TheyWorkForYou ID for someone who isn't already in TheyWorkForYou, i.e. any newly elected candidate who hasn't previously been an MSP or an MLA, for example. We can *probably* work out a nice way of doing this in time, but I wouldn't promise that.

**Comment by dracos** [comment]
The alert lookup does also work for someone's name as a string (you might not realise that as currently it won't work for MP names, but e.g. http://www.theyworkforyou.com/alert/?alertsearch=clare+adamson), and that could almost certainly be streamlined (currently it will ask if you want things by the person or mentions of the person's name, but given they don't refer to each other by name anyway, I doubt you would want that). So if the name is unique, that'd be good enough, it'd just ask for email (and could use design of https://github.com/mysociety/theyworkforyou/pull/818 without postcode in some way).
