### ISSUE TITLE
Ability to delete/merge candidates

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextmp-popit#64]
In my enthusiasm, I went and accidentally duplicated a candidate. Sorry.

<del>http://yournextmp.mysociety.org/constituency/66099/newport-west</del> done

Related to issue #25.

**Comment by tfgg** [comment]
My project using the data is turning up a lot of duplicates, including some subtle ones (that I've verified by checking news stories & photographs) and some tricksy ones like Bill -> William. I'm not going to put them all here because they're pretty easy to find again.

How does the merging thing with the ids and things? Will one of the candidate just be deleted? Will a redirect be left in place?

**Comment by mhl** [comment]
@tfgg: I'll put in a redirect from the old ID (the one that'll be completely deleted from PopIt) on YourNextMP so we're not breaking bookmarks or links - sorry, I've not quite finished this yet.

One more merge reported by email:

http://yournextmp.com/person/2017
http://yournextmp.com/person/4702/gonul-daniels

**Comment by mhl** [comment]
There's a pull request for the "merge" part of this issue here: https://github.com/mysociety/yournextmp-popit/pull/132

In the mean time, here's another pair for merging:
* http://yournextmp.com/person/3859
* http://yournextmp.com/person/5394/dr-rohen-kapur

**Comment by mhl** [comment]
OK, I think we've dealt with all the candidates that need to be merged in this thread. I'm going to close this, and open a new one for a "delete candidate" option. Please open a new ticket for any candidates that need to be merged, and one of the administrators will deal with that.
