### ISSUE TITLE
add CSV export

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#96]
Plenty of people would want to consume the data via a CSV export rather than JSON - the output should be modelled on one of the existing big spreadsheets that people use.

@tfgg and @symroe were talking about this, and it's possible that @tfgg has done something on it already?

**Comment by abimysoc** [comment]
We had an email this morning from someone who could certainly have benefited from this feature, hope it launches soon :+1:

**Comment by mhl** [comment]
@abimysoc It's actually live as of this morning, just not advertised on the front-end yet - if someone needs it, the CSV file for all constituencies is at https://yournextmp.com/media/candidates.csv (license CC-BY-SA)

**Comment by abimysoc** [comment]
:heart:

**Comment by mhl** [comment]
This is mentioned on the "API" page, so I'm going to close this now (although that's not to say we shouldn't promote it more, of course): https://yournextmp.com/help/api
