### ISSUE TITLE
do a bulk mail-out to 2010 candidates whose status is still unknown to ask if they're standing

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#99]
This could either:
* Point them to their page on the site, so they can edit it themselves,
* ask them to reply by email, and we update them ourselves
* or get them to fill in a Google form, and import from the resulting spreadsheet

**Comment by symroe** [comment]
Document for working on this: https://docs.google.com/a/democracyclub.org.uk/document/d/1nGL5NyyX_ZcrZGI2G7GPrZyTy1nuA17_xqjmh70LDtc/edit

**Comment by mhl** [comment]
@symroe set this all up, and it's been remarkably successful: more details here https://democracyclub.org.uk/blog/2015/01/22/emailing-1800-people/
